name: UK - TVGuide

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/download-xmltv-uk-tvguide.yml'
      - 'scripts/**'
#  schedule:
#    - cron: '0 3 * * *'  # every day at midnight

env:
  HOME: /config

jobs:
  scrape-uk-tvguide:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: XMLTV cache
        id: cache-xmltv
        uses: actions/cache@v2
        with:
          path: /config/.xmltv/cache
          key: ${{ runner.os }}-xmltv-cache

      - name: Scrape guide
        run: |
          env

          find /config -type f -exec ls -la {} \;

          ./scripts/get-guide-channels.sh generate-config /config/.xmltv/cache > /config/.xmltv/tv_grab_uk_tvguide.conf
          ./scripts/get-guide-channels.sh generate-mapping > /config/.xmltv/supplement/tv_grab_uk_tvguide/tv_grab_uk_tvguide.map.conf

          find /config/ -type f -exec ls -la {} \;

          mkdir -p xmltv
          /usr/bin/tv_grab_uk_tvguide --days 7 --quiet > xmltv/uk_tvguide.xml
          cat xmltv/uk_tvguide.xml

      - id: name
        run: echo "::set-output name=name::$(date '+%Y%m%d%H%M')"

      - uses: ncipollo/release-action@v1
        # if: ${{ github.event_name == 'cron' }}
        with:
          artifacts: "xmltv/uk_tvguide.xml"
          body: "${{ steps.name.outputs.name }}"
          name: "${{ steps.name.outputs.name }}"
          tag: "${{ steps.name.outputs.name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
