name: UK - TVGuide

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/download-xmltv-uk-tvguide.yml'
#  schedule:
#    - cron: '0 3 * * *'  # every day at midnight

jobs:
  build-xmltv-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Set Environment Variables
        run: |
          echo "whoami: $(whoami)"
          echo "pwd: $(pwd)"
          echo "ls -la:"
          ls -la

      - name: Checkout
        uses: actions/checkout@v2

      - name: XMLTV cache
        id: cache-xmltv
        uses: actions/cache@v2
        with:
          path: /config/.xmltv/cache
          key: ${{ runner.os }}-xmltv-cache

      - name: Scrape guide
        run: |
          export HOME=/config
          mkdir -p /config/.xmltv
          mkdir -p /config/.xmltv/supplement/tv_grab_uk_tvguide

          # ./scripts/get-guide-channels.sh generate-config /config/.xmltv/cache > /config/.xmltv/tv_grab_uk_tvguide.conf
          ./scripts/get-guide-channels.sh generate-mapping > /config/.xmltv/supplement/tv_grab_uk_tvguide/tv_grab_uk_tvguide.map.conf
          cat <<'EOF' > /config/.xmltv/tv_grab_uk_tvguide.conf
          cachedir=/config/.xmltv/cache
          channel=1004
          channel!1011
          EOF

          find $HOME/ -type f -exec ls -la {} \;

          mkdir -p xmltv
          /usr/bin/tv_grab_uk_tvguide --days 1 --quiet > xmltv/uk_tvguide.xml

      - name: Commit new guide
#        if: ${{ github.event_name == 'cron' }}
        run: |
          export HOME=/config
          git add xmltv/uk_tvguide.xml
          git checkout -b testing$(date -u +%Y%M%D%H%M%S)
          git -c user.name='XMLTV CI' -c user.email='xmltv@github.com' commit -m "tv_grab_uk_tvguide $(date -u +%Y%M%D%H%M%S)"
