name: UK - TVGuide

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/download-xmltv-uk-tvguide.yml'
#  schedule:
#    - cron: '0 3 * * *'  # every day at midnight

env:
  HOME: /config

jobs:
  scrape-uk-tvguide:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: XMLTV cache
        id: cache-xmltv
        uses: actions/cache@v2
        with:
          path: /config/.xmltv/cache
          key: ${{ runner.os }}-xmltv-cache

      - name: Scrape guide
        run: |
          env

          find /config -type f -exec ls -la {} \;

          ./scripts/get-guide-channels.sh generate-config /config/.xmltv/cache > /config/.xmltv/tv_grab_uk_tvguide.conf
          ./scripts/get-guide-channels.sh generate-mapping > /config/.xmltv/supplement/tv_grab_uk_tvguide/tv_grab_uk_tvguide.map.conf

          find /config/ -type f -exec ls -la {} \;

          mkdir -p xmltv
          /usr/bin/tv_grab_uk_tvguide --days 1 --quiet > xmltv/uk_tvguide.xml
          cat xmltv/uk_tvguide.xml

      - name: Commit new guide
#        if: ${{ github.event_name == 'cron' }}
        run: |
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          echo git remote set-url origin https://${{ github.repository_owner }}:\${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add xmltv/uk_tvguide.xml
          git -c user.name='XMLTV CI' -c user.email='xmltv@github.com' commit -m "tv_grab_uk_tvguide $(date -u +%Y%m%d%H%M%S)"
          git push origin HEAD
