name: UK - TVGuide

on:
  workflow_dispatch:
    inputs:
      force_release:
        default: "false"
        required: false
        description: "Force a release at the end"
      days:
        default: "1"
        required: false
        description: "Number of days to scrape"
  push:
    paths:
      - '.github/workflows/download-xmltv-uk-tvguide.yml'
      - 'scripts/**'
  schedule:
    - cron: '0 3 * * *'  # every day at 3am

env:
  HOME: /config

jobs:
  scrape-uk-tvguide:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: XMLTV cache
        id: cache-xmltv
        uses: actions/cache@v2
        with:
          path: /config/.xmltv/cache
          key: ${{ runner.os }}-xmltv-cache

      - name: Scrape guide
        run: |
          set -eux

          ./scripts/get-guide-channels.sh generate-config /config/.xmltv/cache > /config/.xmltv/tv_grab_uk_tvguide.conf
          ./scripts/get-guide-channels.sh generate-mapping > /config/.xmltv/supplement/tv_grab_uk_tvguide/tv_grab_uk_tvguide.map.conf

          days=1
          [[ ${{ github.event_name }} == "schedule" ]] && days=7
          [[ ${{ github.event_name }} == "workflow_dispatch" ]] && days=${{ github.event.inputs.days }}

          mkdir -p xmltv
          /usr/bin/tv_grab_uk_tvguide --days "$days" --quiet > xmltv/uk_tvguide.xml
          cat xmltv/uk_tvguide.xml

      - id: name
        name: Determine tag name
        run: |
          if [[ ${{ github.event_name }} == "schedule" ]]; then
            echo "::set-output name=name::$(date '+%Y%m%d')"
          else
            echo "::set-output name=name::$(date '+%Y%m%d%H%M')"
          fi

      - uses: ncipollo/release-action@v1
        if: github.event_name == 'schedule' || github.event.inputs.force_release == 'true'
        with:
          artifacts: "xmltv/uk_tvguide.xml"
          body: "${{ steps.name.outputs.name }}"
          name: "${{ steps.name.outputs.name }}"
          tag: "${{ steps.name.outputs.name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 7
          delete_tags: true
